spring:

  main:
    banner-mode: "off"

  datasource:
    url: jdbc:postgresql://localhost:5432/wolox-training
    username: wolox-training
    password: wolox-training

  flyway:
    locations: "classpath:db/migrations"


  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        #                show_sql: true
        #                format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

server:
  port: 8081
