spring:

  main:
    banner-mode: "off"

  datasource:
    url: jdbc:postgresql://localhost:5432/wolox-training
    username: wolox-training
    password: wolox-training

  flyway:
    locations: "classpath:db/migrations"

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
#        show_sql: true
#        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false


server:
  port: 8081


open-library:
  api:
    base-url: https://openlibrary.org/api
    paths:
      books:
        search-by-isbn: /books?format=json&jscmd=data&bibkeys=ISBN:{isbn}


authentication:
  jwt:
    duration: 3600
    fail_on_invalid: false
    fail_on_blacklisted: false
    allow_anonymous: true
